        function homePage(){
            var shoppingPg = document.getElementById("shopping");
            var recipePage = document.getElementById("recipes");
            var addARecipePg = document.getElementById("addARecipe");
            var allRecipesPg = document.getElementById("allRecipes");
            var favRecipesPg = document.getElementById("favRecipes");
            var ingredientsPg = document.getElementById("ingredientsPageItself");
            var instructionPg = document.getElementById("instructionPageItself");
            var typeInRecipePg = document.getElementById("typeInRecipePageItself");
            var homePg = document.getElementById("homePageItself");
            recipePage.classList.remove("unhidden","hidden");
            recipePage.classList.add("hidden");
            shoppingPg.classList.remove("unhidden","hidden");
            shoppingPg.classList.add("hidden");
            addARecipePg.classList.remove("unhidden","hidden");
            addARecipePg.classList.add("hidden");
            allRecipesPg.classList.remove("unhidden","hidden");
            allRecipesPg.classList.add("hidden");
            favRecipesPg.classList.remove("unhidden","hidden");
            favRecipesPg.classList.add("hidden");
            ingredientsPg.classList.remove("unhidden","hidden");
            ingredientsPg.classList.add("hidden");
            instructionPg.classList.remove("unhidden","hidden");
            instructionPg.classList.add("hidden");
            typeInRecipePg.classList.remove("unhidden","hidden");
            typeInRecipePg.classList.add("hidden");
            homePg.classList.remove("unhidden","hidden");
            homePg.classList.add("unhidden");
        }
        function myRecipes(){
            var recipePage = document.getElementById("recipes");
            var shoppingPg = document.getElementById("shopping");
            var addARecipePg = document.getElementById("addARecipe");
            var allRecipesPg = document.getElementById("allRecipes");
            var favRecipesPg = document.getElementById("favRecipes");
            var ingredientsPg = document.getElementById("ingredientsPageItself");
            var instructionPg = document.getElementById("instructionPageItself");
            var typeInRecipePg = document.getElementById("typeInRecipePageItself");
            var homePg = document.getElementById("homePageItself");
            shoppingPg.classList.remove("hidden","unhidden");
            shoppingPg.classList.add("hidden");
            allRecipesPg.classList.remove("unhidden","hidden");
            allRecipesPg.classList.add("hidden");
            addARecipePg.classList.remove("unhidden","hidden");
            addARecipePg.classList.add("hidden");
            favRecipesPg.classList.remove("unhidden","hidden");
            favRecipesPg.classList.add("hidden");
            ingredientsPg.classList.remove("unhidden","hidden");
            ingredientsPg.classList.add("hidden");
            instructionPg.classList.remove("unhidden","hidden");
            instructionPg.classList.add("hidden");
            typeInRecipePg.classList.remove("unhidden","hidden");
            typeInRecipePg.classList.add("hidden");
            homePg.classList.remove("unhidden","hidden");
            homePg.classList.add("hidden");
            recipePage.classList.remove("hidden","unhidden");
            recipePage.classList.add("unhidden");
        }
        function shoppingPage(){
            var shoppingPg = document.getElementById("shopping");
            var recipePage = document.getElementById("recipes");
            var addARecipePg = document.getElementById("addARecipe");
            var allRecipesPg = document.getElementById("allRecipes");
            var favRecipesPg = document.getElementById("favRecipes");
            var ingredientsPg = document.getElementById("ingredientsPageItself");
            var instructionPg = document.getElementById("instructionPageItself");
            var typeInRecipePg = document.getElementById("typeInRecipePageItself");
            var homePg = document.getElementById("homePageItself");
            recipePage.classList.remove("unhidden","hidden");
            recipePage.classList.add("hidden");
            allRecipesPg.classList.remove("unhidden","hidden");
            allRecipesPg.classList.add("hidden");
            addARecipePg.classList.remove("unhidden","hidden");
            addARecipePg.classList.add("hidden");
            favRecipesPg.classList.remove("unhidden","hidden");
            favRecipesPg.classList.add("hidden");
            ingredientsPg.classList.remove("unhidden","hidden");
            ingredientsPg.classList.add("hidden");
            instructionPg.classList.remove("unhidden","hidden");
            instructionPg.classList.add("hidden");
            typeInRecipePg.classList.remove("unhidden","hidden");
            typeInRecipePg.classList.add("hidden");
            homePg.classList.remove("unhidden","hidden");
            homePg.classList.add("hidden");
            shoppingPg.classList.remove("hidden","unhidden");
            shoppingPg.classList.add("unhidden");
        }
        function addARecipePage(){
            var shoppingPg = document.getElementById("shopping");
            var recipePage = document.getElementById("recipes");
            var addARecipePg = document.getElementById("addARecipe");
            var allRecipesPg = document.getElementById("allRecipes");
            var favRecipesPg = document.getElementById("favRecipes");
            var ingredientsPg = document.getElementById("ingredientsPageItself");
            var instructionPg = document.getElementById("instructionPageItself");
            var typeInRecipePg = document.getElementById("typeInRecipePageItself");
            var homePg = document.getElementById("homePageItself");
            recipePage.classList.remove("unhidden","hidden");
            recipePage.classList.add("hidden");
            shoppingPg.classList.remove("unhidden","hidden");
            shoppingPg.classList.add("hidden");
            allRecipesPg.classList.remove("unhidden","hidden");
            allRecipesPg.classList.add("hidden");
            favRecipesPg.classList.remove("unhidden","hidden");
            favRecipesPg.classList.add("hidden");
            ingredientsPg.classList.remove("unhidden","hidden");
            ingredientsPg.classList.add("hidden");
            instructionPg.classList.remove("unhidden","hidden");
            instructionPg.classList.add("hidden");
            typeInRecipePg.classList.remove("unhidden","hidden");
            typeInRecipePg.classList.add("hidden");
            homePg.classList.remove("unhidden","hidden");
            homePg.classList.add("hidden");
            addARecipePg.classList.remove("unhidden","hidden");
            addARecipePg.classList.add("unhidden");
        }
        function allRecipesPage(){
            var shoppingPg = document.getElementById("shopping");
            var recipePage = document.getElementById("recipes");
            var addARecipePg = document.getElementById("addARecipe");
            var allRecipesPg = document.getElementById("allRecipes");
            var favRecipesPg = document.getElementById("favRecipes");
            var ingredientsPg = document.getElementById("ingredientsPageItself");
            var instructionPg = document.getElementById("instructionPageItself");
            var typeInRecipePg = document.getElementById("typeInRecipePageItself");
            var homePg = document.getElementById("homePageItself");
            recipePage.classList.remove("unhidden","hidden");
            recipePage.classList.add("hidden");
            shoppingPg.classList.remove("unhidden","hidden");
            shoppingPg.classList.add("hidden");
            addARecipePg.classList.remove("unhidden","hidden");
            addARecipePg.classList.add("hidden");
            favRecipesPg.classList.remove("unhidden","hidden");
            favRecipesPg.classList.add("hidden");
            ingredientsPg.classList.remove("unhidden","hidden");
            ingredientsPg.classList.add("hidden");
            instructionPg.classList.remove("unhidden","hidden");
            instructionPg.classList.add("hidden");
            typeInRecipePg.classList.remove("unhidden","hidden");
            typeInRecipePg.classList.add("hidden");
            homePg.classList.remove("unhidden","hidden");
            homePg.classList.add("hidden");
            allRecipesPg.classList.remove("unhidden","hidden");
            allRecipesPg.classList.add("unhidden");
        }
        function favRecipesPage(){
            var shoppingPg = document.getElementById("shopping");
            var recipePage = document.getElementById("recipes");
            var addARecipePg = document.getElementById("addARecipe");
            var allRecipesPg = document.getElementById("allRecipes");
            var favRecipesPg = document.getElementById("favRecipes");
            var ingredientsPg = document.getElementById("ingredientsPageItself");
            var instructionPg = document.getElementById("instructionPageItself");
            var typeInRecipePg = document.getElementById("typeInRecipePageItself");
            var homePg = document.getElementById("homePageItself");
            recipePage.classList.remove("unhidden","hidden");
            recipePage.classList.add("hidden");
            shoppingPg.classList.remove("unhidden","hidden");
            shoppingPg.classList.add("hidden");
            addARecipePg.classList.remove("unhidden","hidden");
            addARecipePg.classList.add("hidden");
            allRecipesPg.classList.remove("unhidden","hidden");
            allRecipesPg.classList.add("hidden");
            ingredientsPg.classList.remove("unhidden","hidden");
            ingredientsPg.classList.add("hidden");
            instructionPg.classList.remove("unhidden","hidden");
            instructionPg.classList.add("hidden");
            typeInRecipePg.classList.remove("unhidden","hidden");
            typeInRecipePg.classList.add("hidden");
            homePg.classList.remove("unhidden","hidden");
            homePg.classList.add("hidden");
            favRecipesPg.classList.remove("unhidden","hidden");
            favRecipesPg.classList.add("unhidden");
        }
        function ingredientsPage(){
            var shoppingPg = document.getElementById("shopping");
            var recipePage = document.getElementById("recipes");
            var addARecipePg = document.getElementById("addARecipe");
            var allRecipesPg = document.getElementById("allRecipes");
            var favRecipesPg = document.getElementById("favRecipes");
            var ingredientsPg = document.getElementById("ingredientsPageItself");
            var instructionPg = document.getElementById("instructionPageItself");
            var typeInRecipePg = document.getElementById("typeInRecipePageItself");
            var homePg = document.getElementById("homePageItself");
            recipePage.classList.remove("unhidden","hidden");
            recipePage.classList.add("hidden");
            shoppingPg.classList.remove("unhidden","hidden");
            shoppingPg.classList.add("hidden");
            addARecipePg.classList.remove("unhidden","hidden");
            addARecipePg.classList.add("hidden");
            allRecipesPg.classList.remove("unhidden","hidden");
            allRecipesPg.classList.add("hidden");
            favRecipesPg.classList.remove("unhidden","hidden");
            favRecipesPg.classList.add("hidden");
            instructionPg.classList.remove("unhidden","hidden");
            instructionPg.classList.add("hidden");
            typeInRecipePg.classList.remove("unhidden","hidden");
            typeInRecipePg.classList.add("hidden");
            homePg.classList.remove("unhidden","hidden");
            homePg.classList.add("hidden");
            ingredientsPg.classList.remove("unhidden","hidden");
            ingredientsPg.classList.add("unhidden");
        }
        function instructionPage(){
            var shoppingPg = document.getElementById("shopping");
            var recipePage = document.getElementById("recipes");
            var addARecipePg = document.getElementById("addARecipe");
            var allRecipesPg = document.getElementById("allRecipes");
            var favRecipesPg = document.getElementById("favRecipes");
            var ingredientsPg = document.getElementById("ingredientsPageItself");
            var instructionPg = document.getElementById("instructionPageItself");
            var typeInRecipePg = document.getElementById("typeInRecipePageItself");
            var homePg = document.getElementById("homePageItself");
            recipePage.classList.remove("unhidden","hidden");
            recipePage.classList.add("hidden");
            shoppingPg.classList.remove("unhidden","hidden");
            shoppingPg.classList.add("hidden");
            addARecipePg.classList.remove("unhidden","hidden");
            addARecipePg.classList.add("hidden");
            allRecipesPg.classList.remove("unhidden","hidden");
            allRecipesPg.classList.add("hidden");
            favRecipesPg.classList.remove("unhidden","hidden");
            favRecipesPg.classList.add("hidden");
            ingredientsPg.classList.remove("unhidden","hidden");
            ingredientsPg.classList.add("hidden");
            typeInRecipePg.classList.remove("unhidden","hidden");
            typeInRecipePg.classList.add("hidden");
            homePg.classList.remove("unhidden","hidden");
            homePg.classList.add("hidden");
            instructionPg.classList.remove("unhidden","hidden");
            instructionPg.classList.add("unhidden");
        }
        function typeInRecipePage(){
            var shoppingPg = document.getElementById("shopping");
            var recipePage = document.getElementById("recipes");
            var addARecipePg = document.getElementById("addARecipe");
            var allRecipesPg = document.getElementById("allRecipes");
            var favRecipesPg = document.getElementById("favRecipes");
            var ingredientsPg = document.getElementById("ingredientsPageItself");
            var instructionPg = document.getElementById("instructionPageItself");
            var typeInRecipePg = document.getElementById("typeInRecipePageItself");
            var homePg = document.getElementById("homePageItself");
            recipePage.classList.remove("unhidden","hidden");
            recipePage.classList.add("hidden");
            shoppingPg.classList.remove("unhidden","hidden");
            shoppingPg.classList.add("hidden");
            addARecipePg.classList.remove("unhidden","hidden");
            addARecipePg.classList.add("hidden");
            allRecipesPg.classList.remove("unhidden","hidden");
            allRecipesPg.classList.add("hidden");
            favRecipesPg.classList.remove("unhidden","hidden");
            favRecipesPg.classList.add("hidden");
            ingredientsPg.classList.remove("unhidden","hidden");
            ingredientsPg.classList.add("hidden");
            instructionPg.classList.remove("unhidden","hidden");
            instructionPg.classList.add("hidden");
            homePg.classList.remove("unhidden","hidden");
            homePg.classList.add("hidden");
            typeInRecipePg.classList.remove("unhidden","hidden");
            typeInRecipePg.classList.add("unhidden");
        }